name: Build and deploy React app to Azure Web App - sotr-frontend-web

on:
  push:
    branches:
      - clean-main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install and build frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Prepare deploy folder (STATIC ONLY)
        run: |
          rm -rf deploy
          mkdir deploy
          cp -r frontend/build/* deploy/

      - name: Zip deploy package
        working-directory: deploy
        run: |
          zip -r ../site.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sotr-frontend-web'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_15306AB08EE24FCEB29266DFB45F0092 }}
          package: site.zip
